name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  shared_preferences: ^0.5.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/app_developer_image1.png
    - enjoy_image1.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf